thunder_media.settings:
  type: config_object
  mapping:
    enable_filename_transliteration:
      type: boolean
      label: 'Default transliteration'
    enable_filefield_remove_button:
      type: boolean
      label: 'Enable remove button'

image.effect.thunder_media_auto_aspect:
  type: mapping
  label: 'Auto Aspect'
  mapping:
    landscape:
      type: string
      label: 'Landscape image style'
    portrait:
      type: string
      label: 'Portrait'
    ratio_adjustment:
      type: integer
      label: 'Ratio adjustment'
