name: Check coding styles

on:
  pull_request:
    paths:
      - '**.js'
      - '**.php'
      - '**.module'
      - '**.profile'
      - '**.theme'

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check

  phpcs:
    name: runner / phpcs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: phpcs
        uses: chrfritsch/action-drupal-coder@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          filter_mode: nofilter
